package config

import "time"

const (

	// DefaultPageTitle templates this title into the page so you can change title as required
	DefaultPageTitle = "8k.fyi"
	// DefaultAccentColour templates this colour into the HTML to accent the page with this colour
	DefaultAccentColour = "#FF8C00"
	// DefaultMaxBytes is the max bytes that the site will accept. This is enforced both in the frontend and the backend (because we don't trust the client)
	DefaultMaxBytes = 8192
	// DefaultMaxItems is the max number of items the site will accept. This multiplied by the MaxBytes gives a value for storage requirement.
	DefaultMaxItems = 1000
	// DefaultPathLength is used to set the length of autogenerated paths for the link address
	DefaultPathLength = 8

	// DefaultBindTLS sets whether the server should bind TLS by default
	DefaultBindTLS = false
	// DefaultBindAddress is the default address to bind the server to. Empty bind will bind all available addresses
	DefaultBindAddress = ""
	// DefaultBindPort is the dedault port to bind the server to.
	DefaultBindPort = 8192

	// DefaultPublicProtoTLS is used if you're terminating TLS at a reverse proxy (e.g. NGINX, Apache)
	// This proto is templated into the HTML for public use
	DefaultPublicProtoTLS = DefaultBindTLS
	// DefaultPublicAddress is used if you're NATing (e.g. Docker) and your public address is different from the bind address
	// This address is templated into the HTML for public use
	DefaultPublicAddress = ""
	// DefaultPublicPort is used if you're NATing (e.g. Docker) and your public port is different from the bind port
	// This port is templated into the HTML for public use
	DefaultPublicPort = 8192

	// DefaultTTL is the default expiry time for data in storage
	DefaultTTL = time.Minute * 60

	// DefaultTLSCertFilePath is the default path for the TLS certificate file
	DefaultTLSCertFilePath = "/tls/public.crt"
	// DefaultTLSKeyFilePath is the default path for the TLS key file
	DefaultTLSKeyFilePath = "/tls/private.key"

	// DefaultIndexFilePath is the default location for the html frontend
	DefaultIndexFilePath = "/frontend/index.html"
)
