package flags

import (
	"8192bytes/pkg/config"
	"flag"
)

var (
	// Version of the server. Set at build time using -ldflags "-X main.version=<version number>"
	Version = "development"

	// ShowVersion displays the version and exits, when provided
	ShowVersion = flag.Bool("v", false, "show version")

	//DataTTL sets the time to keep data before deleting
	DataTTL = flag.Duration("ttl", config.DefaultTTL, "the time before an uploaded data item expires and is deleted")

	// PageTitle allows overriding the default page title in the UI
	PageTitle = flag.String("title", config.DefaultPageTitle, "set the title of the web page")
	// AccentColour allows overriding the beautiful orange accent colour
	AccentColour = flag.String("accent-colour", config.DefaultAccentColour, "set the accent colour for the web page")
	// MaxBytes allows overriding the carefully chosen 8192 byte limit for uploads
	MaxBytes = flag.Int("mb", config.DefaultMaxBytes, "override the max bytes count")
	//MaxItemsStored sets the maximum number of items to store before disallowing any further storage until some have been scrubber
	MaxItemsStored = flag.Int("mi", config.DefaultMaxItems, "set the maximum number of items to store before disallowing")
	// PathLength is used to set the length of the auto-generated path part of the URL
	PathLength = flag.Int("pl", config.DefaultPathLength, "override autogenerated path length")
	// BindTLS enables TLS directly in the server. Do not enable this if using a reverse proxy such as Nginx/Traefik
	BindTLS = flag.Bool("https", config.DefaultBindTLS, "enable TLS")
	// BindAddress overrides the default bind address
	BindAddress = flag.String("addr", config.DefaultBindAddress, "set the bind address")
	// BindPort overrides the default bind port of the server
	BindPort = flag.Int("port", config.DefaultBindPort, "set the bind port")

	// PublicProtoTLS sets whether to use 'https' for links in the UI
	PublicProtoTLS = flag.Bool("ui-https", false, "UI: use 'https' as the proto displayed in the UI text/links")
	// PublicAddress sets the address or hostname used in the UI
	PublicAddress = flag.String("ui-addr", config.DefaultPublicAddress, "UI: set the public address displayed in the UI text/links")
	// PublicPort sets the port used in the UI
	PublicPort = flag.Int(("ui-port"), config.DefaultPublicPort, "UI: set the public port displayed in the UI/text/links")

	// UIFileHTML is the path to the HTML file for the UI
	UIFileHTML = flag.String("html", config.DefaultIndexFilePath, "set the path to the index html template file for the frontend")

	// TLSCertFile set the location of the TLS certificate file for binding TLS
	TLSCertFile = flag.String("tls-cert", config.DefaultTLSCertFilePath, "path to the TLS certificate")
	// TLSKeyFile sets the location of the TLS key file for binding TLS
	TLSKeyFile = flag.String("tls-key", config.DefaultTLSKeyFilePath, "path to the TLS key")
)
